name: chat_app
description: "A new Flutter project."

# Prevent accidental publication to pub.dev
publish_to: 'none' 

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.15
  contacts_service: ^0.6.3
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  image_picker: ^1.1.2
  haptic_feedback: ^0.5.1+1
  http: ^1.3.0
  cached_network_image: ^3.3.0
  flutter_shimmer: ^2.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/fonts/

  # Uncomment to add custom fonts
  # fonts:
  #   - family: SF Pro
  #     fonts:
  #       - asset: assets/fonts/SF-Pro-Display-Regular.otf
  #       - asset: assets/fonts/SF-Pro-Display-Bold.otf
  #         weight: 700
  #       - asset: assets/fonts/SF-Pro-Display-Semibold.otf
  #         weight: 600

  uses-material-design: true
