// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFUnTqZtgeOPCaD0xshvKUpFoLglQp3gA',
    appId: '1:23321835003:web:b0418b0fa4d38cbfba075e',
    messagingSenderId: '23321835003',
    projectId: 'z-app-6e5e0',
    authDomain: 'z-app-6e5e0.firebaseapp.com',
    storageBucket: 'z-app-6e5e0.firebasestorage.app',
    measurementId: 'G-L4E2R1C0J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIYAxLWBYCW33B5cqiGvIXefMCIA55q-I',
    appId: '1:321677675955:android:48ac3087dee1b0bd35cfc6',
    messagingSenderId: '321677675955',
    projectId: 'zapp-71716',
    storageBucket: 'zapp-71716.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFdmOot2ieB-Uez-q17Xjzipn7lBlNkVY',
    appId: '1:321677675955:ios:467d82ac6f1770ec35cfc6',
    messagingSenderId: '321677675955',
    projectId: 'zapp-71716',
    storageBucket: 'zapp-71716.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFdmOot2ieB-Uez-q17Xjzipn7lBlNkVY',
    appId: '1:321677675955:ios:467d82ac6f1770ec35cfc6',
    messagingSenderId: '321677675955',
    projectId: 'zapp-71716',
    storageBucket: 'zapp-71716.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgJ9HS9NOsfwxYG3j5331Zqhc23cCJIdQ',
    appId: '1:321677675955:web:5255c95e006b789035cfc6',
    messagingSenderId: '321677675955',
    projectId: 'zapp-71716',
    authDomain: 'zapp-71716.firebaseapp.com',
    storageBucket: 'zapp-71716.firebasestorage.app',
    measurementId: 'G-0N94MEDQTX',
  );

}